.PHONY: default
default: beamercolorthemebluejay.sty beamercolorthemebluejay.pdf

beamercolorthemebluejay.pdf: beamercolorthemebluejay.sty example.pdf

example.pdf: beamercolorthemebluejay.sty

include ../../../../Makefile.mk
